name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'scripts/**'
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: production_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: pnpm build-prod --verbose

      - name: Build project
        run: rojo build ./build.project.json --output place.rbxlx

      - name: Upload place
        uses: actions/upload-artifact@v4
        with:
          name: place
          path: place.rbxlx

  deploy:
    runs-on: self-hosted
    environment: production
    needs: build

    steps:
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.2.0

      - uses: actions/checkout@v4
      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download place artifact
        uses: actions/download-artifact@v3
        with:
          name: place

      - name: Deploy game
        run: mantle deploy --allow-purchases --environment production
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_AWS_ACCESS_KEY_ID: ${{ secrets.MANTLE_AWS_ACCESS_KEY_ID }}
          MANTLE_AWS_SECRET_ACCESS_KEY: ${{ secrets.MANTLE_AWS_SECRET_ACCESS_KEY }}
